### PR TITLE
Reorganize .travis.yml like in the GEOSX repo.

### PR DESCRIPTION
**Pull request by TotoGaz**
No need to update GEOSX, just a yaml reorganization.
Validated through travis build https://app.travis-ci.com/github/GEOSX/GEOSX/builds/238959430

### CODE REVIEW

**Review by francoishamon — APPROVED** [review]
That looks good to me, although I would probably not be able to catch an error here :)

**Comment by TotoGaz** [comment]
Hello @bmhan12 are you available for the review?

**Review by bmhan12 — APPROVED** [review]
@TotoGaz  Looks good to me! Thanks for verifying with GEOSX CI tests.

**Comment by TotoGaz** [comment]
Thx @bmhan12 !

**Pull request merged**
