### PR TITLE
Removing PETSc dependency from SuiteSparse

### PR DESCRIPTION
**Pull request by af1990**
Removing useless dependency.

### CODE REVIEW

**Comment by TotoGaz** [comment]
Does keeping `SuiteSparse` makes sense or shall we remove it too?

**Comment by castelletto1** [comment]
> Does keeping `SuiteSparse` makes sense or shall we remove it too?

Yes, we will keep `SuiteSparse` (see https://github.com/GEOSX/GEOSX/pull/1169#issuecomment-703930170).

**Review by castelletto1 — APPROVED** [review]

**Comment by af1990** [comment]
The main idea is that we want a sequential direct solver: UMFPACK, from SuiteSparse. This algorithm is quite successful, being widely used (e.g., Matlab backslash is an UMFPACK call).
PETSc offers an interface to UMFPACK, but it is not flexible enough to allow us, for example, to access the estimate of the condition number that UMFPACK would provide.
This is why in a first implementation I was using this PETSc interface (hence the dependency), but then I provided a GEOSX interface to UMFPACK, more flexible and suited to out needs. So now there is no need of the PETSc interface to UMFPACK anymore, but UMFPACK (and therefore SuiteSparse) is still used.

**Comment by corbett5** [comment]
@af1990 Are you the one who built the most recent TPLs on LC? On 2020-10-05?

**Comment by af1990** [comment]
> 
> 
> @af1990 Are you the one who built the most recent TPLs on LC? On 2020-10-05?

No, I've never built the TPLs on LC.

**Comment by corbett5** [comment]
Cool, do you mind if I tack on a RAJA update to this PR? That way we won't have to rebuild them a second time.

**Comment by castelletto1** [comment]
> Cool, do you mind if I tack on a RAJA update to this PR? That way we won't have to rebuild them a second time.

Sounds good to me. Once GEOSX/GEOSX#1169 gets approved, I can take

**Comment by corbett5** [comment]
@castelletto1 I'll rebuild on LC and push the new host configs to GEOSX/GEOSX#1169.

**Comment by af1990** [comment]
> Cool, do you mind if I tack on a RAJA update to this PR? That way we won't have to rebuild them a second time.

Not at all. For me it's ok.

**Comment by castelletto1** [comment]
@corbett5 : if you update host configs in GEOSX/GEOSX#1169 and LvArray, I will only have to take care of rebaselining the integrated tests on quartz.

**Comment by corbett5** [comment]
@castelletto1 @af1990 is it okay if I merge this? My PR https://github.com/GEOSX/GEOSX/pull/1196 relies on the TPL update.

**Comment by af1990** [comment]
Also PR GEOSX/GEOSX#1169 needs it. For me it's ok!

**Comment by castelletto1** [comment]
@corbett5 yes, go ahead.

**Pull request merged**
