### PR TITLE
Remove scotch parallel build

### PR DESCRIPTION
**Pull request by XL64**
Related to https://github.com/GEOSX/GEOSX/pull/2038.

Solves https://github.com/GEOSX/GEOSX/issues/2024

### CODE REVIEW

**Comment by TotoGaz** [comment]
I'm fine with this, but it's strange.
@klevzoff did you witness this already?

**Comment by klevzoff** [comment]
I have not encountered any problems with parallel build so far, on local machines or the cluster. I would be honestly quite surprised if that was the reason, since it's a pretty standard battle-hardened parallel make. In my experience parallel build problems are usually caused by underlying hw/os/fs issues like clock desync between storage and compute nodes. What do the build failures look like on Pangea3?

Scotch doesn't take too long to build in serial. On my PC it takes
  * 31.286 s with `NUM_PROC=1`
  *  7.848 s with `NUM_PROC=8`

This is acceptable, given our overall build times with things like Trilinos and VTK. We could implement a more nuanced host-config based solution in which Pangea3 host-config would define `SCOTCH_NUM_PROC=1` while allowing everyone else to still build in parallel. But I won't insist on it.

**Comment by XL64** [comment]
Hello,

I Can Do a specific change for pangea3 Indeed.
I got one .o fille randomly missing when linking the lib.

Regards,

XL

Le mer. 24 août 2022, 05:23, Sergey Klevtsov ***@***.***> a
écrit :

**Comment by XL64** [comment]
Not working, the if (NOT DEFINED SCOTCH_NUM_PROC) does not work.

**Comment by XL64** [comment]
Works fine on P3, RelWithDebInfo, Release, Debug until GEOSX tests (which fails because some tests fail but not link to PR)
The following tests FAILED:
	 60 - testMath (Failed)
	107 - testDruckerPrager (Failed)
	109 - testModifiedCamClay (Failed)
	119 - testLinearAlgebra_KrylovSolvers (Timeout)
	149 - testTriaxial_druckerPragerExtended (Failed)
	152 - testTriaxial_modifiedCamClay (Failed)
	153 - testTriaxial_delftEggUseLinear (Failed)
	154 - testTriaxial_modifiedCamClayVolumetric (Failed)
	155 - testTriaxial_delftEggLoadPathDryUseLinear (Failed)
	156 - testTriaxial_delftEggLoadPathWetUseLinear (Failed)
	157 - testTriaxial_delftEggCase1 (Failed)
	158 - testTriaxial_delftEggCase2 (Failed)

**Review by klevzoff — APPROVED** [review]

**Comment by TotoGaz** [comment]
@klevzoff @XL64 I'm merging?

**Comment by TotoGaz** [comment]
> Works fine on P3, RelWithDebInfo, Release, Debug until GEOSX tests (which fails because some tests fail but not link to PR)
> The following tests FAILED:
> 60 - testMath (Failed)
> 107 - testDruckerPrager (Failed)
> 109 - testModifiedCamClay (Failed)
> 119 - testLinearAlgebra_KrylovSolvers (Timeout)
> 149 - testTriaxial_druckerPragerExtended (Failed)
> 152 - testTriaxial_modifiedCamClay (Failed)
> 153 - testTriaxial_delftEggUseLinear (Failed)
> 154 - testTriaxial_modifiedCamClayVolumetric (Failed)
> 155 - testTriaxial_delftEggLoadPathDryUseLinear (Failed)
> 156 - testTriaxial_delftEggLoadPathWetUseLinear (Failed)
> 157 - testTriaxial_delftEggCase1 (Failed)
> 158 - testTriaxial_delftEggCase2 (Failed)

Can you open an issue? We need to investigate a little.

**Review by TotoGaz — APPROVED** [review]

**Pull request merged**
