### PR TITLE
Remove tplMirror

### PR DESCRIPTION
**Pull request by TotoGaz**
Fixes https://github.com/GEOSX/thirdPartyLibs/issues/122.

We have now a `yaml` file describing all our TPLs and where to download them (when I could find them/the version).
Still work in progress.

We can use this `yaml` to impose an non-versioned name for the tarballs, like I did for `doxygen`.
For example, `https://github.com/doxygen/doxygen/archive/Release_1_8_13.tar.gz` will de downloaded into "_anonymous_" file `doxygen.tar.gz`, and file `CMakeLists.txt` is asked to use `doxygen.tar.gz`.
So we do not have to modify `CMakeLists.txt` to update a version, it is defined in a single place.
It's nice but honestly I don't think anyone never had any problem with that. This is solving a non-problem.

**Q1: Do we want this?**

Warning, **non-release** tarballs from `github.com` (a link like https://github.com/LLNL/Adiak/archive/v0.2.0.tar.gz) do not contain the submodules. While **release** links do (like https://github.com/LLNL/Adiak/releases/download/v0.2.0/adiak-0.2.0.tar.gz).
This must be a point of attention for us since our bundles in `tplMirror` do have those `submodules`.
As such, we must be careful when using a direct download from github.

We'll have some vicious issues like: I'm using an official release of a TPL, I want to use a specific branch so I change the URL... _fatalitas_, I do not have the submodules and the dev bangs his head against the walls to understand what's going on.
We should play with patches there... Complicated.
I don't know if that happens too often.

**Q2 I can see multiple options here**
1. Keep complete `tplMirror` because it was easy to use
2. Completely do the new way. I can add a warning in case of potential submodules issues.
3. Do the new way and keep potential `tplMirror` in case we "have to".
4. Use `cmake`'s "_embedded_" download feature (`git` + `http`) to clone what we want. No more offline solution.

EDIT:
There are md5 mismatches for some bundles.

```bash
> diff -qr Adiak-ref Adiak-yaml
Only in Adiak-ref/blt: .git
Only in Adiak-yaml: scripts
```
```bash
> diff -qr hdf5-1.10.5-ref hdf5-1_10_5-yaml
Only in hdf5-1_10_5-yaml: .autom4te.cfg
Only in hdf5-1_10_5-yaml: .gitattributes
Only in hdf5-1_10_5-yaml: .gitignore
Only in hdf5-1_10_5-yaml: .h5chkright.ini
Only in hdf5-1.10.5-ref: Makefile
Only in hdf5-1_10_5-yaml/bin: README
Only in hdf5-1_10_5-yaml/bin: bbrelease
Only in hdf5-1_10_5-yaml/bin: checkapi
Only in hdf5-1_10_5-yaml/bin: checkposix
Only in hdf5-1_10_5-yaml/bin: chkconfigure
Only in hdf5-1_10_5-yaml/bin: chkcopyright
Only in hdf5-1_10_5-yaml/bin: debug-ohdr
Only in hdf5-1_10_5-yaml/bin: errors
Only in hdf5-1_10_5-yaml/bin: gcov_script
Only in hdf5-1_10_5-yaml/bin: pkgscrpts
Files hdf5-1.10.5-ref/bin/release and hdf5-1_10_5-yaml/bin/release differ
Only in hdf5-1_10_5-yaml/bin: runbkgprog
Only in hdf5-1_10_5-yaml/bin: runtest
Only in hdf5-1_10_5-yaml/bin: snapshot_version
Only in hdf5-1_10_5-yaml/bin: switch_maint_mode
Only in hdf5-1_10_5-yaml/bin: timekeeper
Files hdf5-1.10.5-ref/release_docs/RELEASE.txt and hdf5-1_10_5-yaml/release_docs/RELEASE.txt differ
Only in hdf5-1_10_5-yaml/src: .indent.pro
Only in hdf5-1_10_5-yaml/src: hdf5-lin.lnt
Only in hdf5-1_10_5-yaml/src: hdf5-win.lnt
Only in hdf5-1_10_5-yaml/src: hdf5.lnt
```
There are more scripts in the "new" version.
File `bin/release` differs since they point to different version of examples.
About `Only in hdf5-1.10.5-ref: Makefile`, this `Makefile` seems generated by the mew version (`config.status: creating Makefile` in the logs)

```bash
> diff -qr hypre-ref hypre-yaml
```
Nothing different for hypre 🤷 . Maybe some metainformations?

```bash
> diff -qr pugixml-ref pugixml-yaml
Only in pugixml-ref: .codecov.yml
Only in pugixml-ref: .gitignore
Only in pugixml-ref: .travis.yml
Files pugixml-ref/CMakeLists.txt and pugixml-yaml/CMakeLists.txt differ
Only in pugixml-ref: Makefile
Only in pugixml-ref: README.md
Only in pugixml-ref: appveyor.yml
Only in pugixml-ref/docs: config.adoc
Only in pugixml-ref/docs: manual.adoc
Files pugixml-ref/docs/manual.html and pugixml-yaml/docs/manual.html differ
Only in pugixml-ref/docs: quickstart.adoc
Files pugixml-ref/docs/quickstart.html and pugixml-yaml/docs/quickstart.html differ
Files pugixml-ref/readme.txt and pugixml-yaml/readme.txt differ
Only in pugixml-ref/scripts: archive.py
Only in pugixml-ref/scripts: nuget
Only in pugixml-yaml/scripts: nuget.autopkg
Only in pugixml-yaml/scripts: nuget_build.bat
Only in pugixml-ref/scripts: nuget_build.ps1
Files pugixml-ref/scripts/pugixml.podspec and pugixml-yaml/scripts/pugixml.podspec differ
Files pugixml-ref/scripts/pugixml_airplay.mkf and pugixml-yaml/scripts/pugixml_airplay.mkf differ
Files pugixml-ref/scripts/pugixml_vs2010.vcxproj and pugixml-yaml/scripts/pugixml_vs2010.vcxproj differ
Files pugixml-ref/scripts/pugixml_vs2010_static.vcxproj and pugixml-yaml/scripts/pugixml_vs2010_static.vcxproj differ
Files pugixml-ref/scripts/pugixml_vs2013.vcxproj and pugixml-yaml/scripts/pugixml_vs2013.vcxproj differ
Files pugixml-ref/scripts/pugixml_vs2013_static.vcxproj and pugixml-yaml/scripts/pugixml_vs2013_static.vcxproj differ
Only in pugixml-ref/scripts: pugixml_vs2015_static.vcxproj
Only in pugixml-ref/scripts: pugixml_vs2017.vcxproj
Only in pugixml-ref/scripts: pugixml_vs2017_static.vcxproj
Files pugixml-ref/src/pugiconfig.hpp and pugixml-yaml/src/pugiconfig.hpp differ
Files pugixml-ref/src/pugixml.cpp and pugixml-yaml/src/pugixml.cpp differ
Files pugixml-ref/src/pugixml.hpp and pugixml-yaml/src/pugixml.hpp differ
Only in pugixml-ref: tests
```
Some modifications about building (sometimes carriage returns...) or docs, nothing to be concerned about.

```bash
> diff -qr superlu_dist-ref superlu_dist-yaml
```
Nothing for `superli_dist`, probably file metainformations too.

```bash
>  diff -qr uncrustify-ref uncrustify-yaml
Files uncrustify-ref/CMakeLists.txt and uncrustify-yaml/CMakeLists.txt differ
Files uncrustify-ref/forUncrustifySources.cfg and uncrustify-yaml/forUncrustifySources.cfg differ
Files uncrustify-ref/src/align_func_params.cpp and uncrustify-yaml/src/align_func_params.cpp differ
Files uncrustify-ref/src/combine.cpp and uncrustify-yaml/src/combine.cpp differ
Files uncrustify-ref/src/combine.h and uncrustify-yaml/src/combine.h differ
Files uncrustify-ref/src/indent.cpp and uncrustify-yaml/src/indent.cpp differ
Files uncrustify-ref/src/output.cpp and uncrustify-yaml/src/output.cpp differ
Files uncrustify-ref/src/quick_align_again.cpp and uncrustify-yaml/src/quick_align_again.cpp differ
Only in uncrustify-ref/src: remove_extra_returns.cpp
Only in uncrustify-ref/src: remove_extra_returns.h
Files uncrustify-ref/src/uncrustify.cpp and uncrustify-yaml/src/uncrustify.cpp differ
Files uncrustify-ref/tests/c-sharp.test and uncrustify-yaml/tests/c-sharp.test differ
Files uncrustify-ref/tests/cli/output/p.txt and uncrustify-yaml/tests/cli/output/p.txt differ
Files uncrustify-ref/tests/cli/output/pc-.txt and uncrustify-yaml/tests/cli/output/pc-.txt differ
Only in uncrustify-ref/tests/config: Issue_2705.cfg
Only in uncrustify-ref/tests/expected/cs: 12108-Issue_2705.cs
Only in uncrustify-ref/tests/input/cs: Issue_2705.cs
```
For `uncrustify` there are small differences.
```bash
>  diff uncrustify-ref/CMakeLists.txt uncrustify-yaml/CMakeLists.txt                                                                                1 ↵
288d287
<   src/remove_extra_returns.cpp
335d333
<   src/combine.h
356d353
<   src/remove_extra_returns.h
```
or
```bash
>  diff uncrustify-ref/forUncrustifySources.cfg uncrustify-yaml/forUncrustifySources.cfg
310,311c310
< #mod_remove_empty_return                   = true
< mod_remove_empty_return                   = false
---
> mod_remove_empty_return                   = true
```
`uncrustify` was updated in https://github.com/GEOSX/thirdPartyLibs/pull/102 last time, and it looks like there was some hack.
It's weird, it's like commit https://github.com/uncrustify/uncrustify/commit/04f28db0d606ec8257a428f2fcc2f3af97229ade (+ some indentation) had not been considered.

### CODE REVIEW

**Review by cssherman — DISMISSED** [review]
Looks great!  My only suggestion is that you may consider mirroring the doxygen-style tags in the docstrings like we've done in some of the other python scripts.  For example, from the hdf5_wrapper:

```python
def __init__(self, fname='', target='', mode='r'):
    """
    @brief initialize the hdf5_wrapper class
    @param fname the filename of a new or existing hdf5 database
    @param target the handle of an existing hdf5 dataset
    @param mode the read/write behavior of the database (default='r')
    @details If the fname is supplied (either by a positional or keyword argument),
             the wrapper will open a hdf5 database from the filesystem.  The reccomended
             options for the mode flag include 'r' for read-only and 'a' for read/write
             access.  If write mode is enabled, and the fname does not point
             to an existing file, a new database will be created.
             If the target is supplied, then a new instance of the wrapper will
             be created using an existing database handle.
    """
    pass
```

**Review by rrsettgast — DISMISSED** [review]

**Comment by rrsettgast** [comment]
> Hello,
> 
> I suggest that for every `travis-ci` build of the TPLs, we have a separate stage (at the end) which uploads all the tarballs listed in the `tpls.yaml` to a GCP bucket. (I can try to make the upload smart to save some bandwidth and little money.)
> 
> We will have files in the bucket which are not needed anymore, files which may have never been needed.
> But the size of the data is so little that we shall not bother about that (it should cost a fistful of cents per year).
> We can manage a cleanup once a year.
> 
> The files will be kept private by default: it’s a backup, no need to expose them.
> I can make them public at will.
> 
> To use a new TPL you just have to add an input in the `yaml` config file; and the backup will be generated.
> To activate the backup you just have to change the URL in the `yaml` config file and make the targeted URL public.
> 
> This means no `git-lfs`, no submodules.
> I believe it’s the best solution when it comes to maintenance, ease of use, ease of development.
> 
> Any comments before I move on?

Doesn't this mean that for someone to use the backup, then have to:
1. edit the `yaml` config file,
2. contact you to make the bucket public?

**Comment by TotoGaz** [comment]
> Doesn't this mean that for someone to use the backup, then have to:
> 
> 1. edit the `yaml` config file,
> 2. contact you to make the bucket public?

Yes, as described, that's it.
I can make the bucket public if you want to. I need to monitor it carefully since it is an endless money pit.
I do not think I can do anything about point 1.

**Comment by rrsettgast** [comment]
@TotoGaz that sounds like more work than the submodule? If you are happy with it, then go ahead. We may have to revise the plan later. Hopefully we never have a need for the backup, all of this is unnecessary.

**Comment by TotoGaz** [comment]
> @TotoGaz that sounds like more work than the submodule? If you are happy with it, then go ahead. We may have to revise the plan later. Hopefully we never have a need for the backup, all of this is unnecessary.

Hi @rrsettgast 

Actually, I think this is less work than the submodules.
To my eyes, what foremost matters here is the number of different flow, options, cases.

In the pattern I suggest, there is one unique flow for everyone and everything. But it’s still flexible.
To add (and automatically backup) a TPL, modify the `tpls.yaml` file.
To use a backuped tarball, modify the `tpls.yaml` and change the URL.
This has some value.

Thus, I have far less documentation (on readthedocs) to write: a proper documentation in the code should be enough.

And as per the upload part itself, the code that matters is ~15 lines of pure python. (The rest is command line argument, parsing, doc, logging; same for all solutions).

A `git submodule` solution would force me to deal with cases where the `submodule` is activated or not (Running a `git` command? Check if there are some files? What if remaining junk is there ?).
I must deal with the case where `git-lfs` has not been activated too (the file is here but just metadata).
Maybe I should set some PR submodule protection up like we did for https://github.com/GEOSX/GEOSX too?
Maybe should I be able to test multiple cases in the CI too?
I must tell everyone how it’s working so they can change the TPLs themselves.
And I must provide comprehensive error messages if I do not want to be bothered too much with support.

So globally, if I manage to make it work, I think the GCP bucket solution is simpler.
It’s indeed ready and (i think) debugged (even though we’re never sure :wink:).
I do not think I would have done it so fast with submodules.

**Review by rrsettgast — APPROVED** [review]
@bmhan12 Can you give this a review?

**Review by bmhan12 — APPROVED** [review]
LGTM!

**Comment by TotoGaz** [comment]
@rrsettgast I'm ready to merge. Are you sure nothing needs to be anticipated on LLNL side? (`git lfs` is no more enough).

**Comment by TotoGaz** [comment]
Hi @corbett5 !

You therefore need to run
```
python3 ${TRAVIS_BUILD_DIR}/scripts/download_prerequisites.py 
  --tpl=${TRAVIS_BUILD_DIR}/scripts/tpls.yaml
  --dest=${TRAVIS_BUILD_DIR}/tplMirror
```
after the `git-lfs` part (which is not totally remove for now).
If you run the script from the root directory of the TPL clone, it should be OK (_i.e._ change `scripts/tpls.yaml` into `scripts/tpls.yaml`).

If you need to define some `http_proxy` env variable, `python`'s `request` module that is used should deal it for us.

**Comment by corbett5** [comment]
So I tried building on Quartz with clang 10 and I ran into some issues. First of when running the python script I encountered this hard error. I removed the argument and it progressed until I reached the net error
```
[2020/10/13 00:28:32][   ERROR] module 'yaml' has no attribute 'FullLoader'
```

```
 > python3 ./scripts/download_prerequisites.py --tpl=./scripts/tpls.yaml --dest=./tplMirror
[2020/10/13 00:31:14][    INFO] Downloading https://github.com/LLNL/Adiak/releases/download/v0.2.0/adiak-0.2.0.tar.gz to ./tplMirror/adiak.tar.gz
[2020/10/13 00:31:14][    INFO] Checksum for ./tplMirror/adiak.tar.gz matches reference.
[2020/10/13 00:31:14][ WARNING] No url provided for tpl "asm-jit.tar.gz". Nothing done.
[2020/10/13 00:31:15][   ERROR] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
Traceback (most recent call last):
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/download_prerequisites.py", line 148, in download_tpl
    response = session.get(url, stream=True)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/requests/adapters.py", line 527, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```

This didn't abort the program so after it finished I tried to actually build but I ran into this error

```
[ 23%] Performing download step (verify and extract) for 'astyle'
CMake Error at astyle-stamp/verify-astyle.cmake:11 (message):
  File not found: /usr/WS2/corbett5/tpl-totogaz/tplMirror/astyle.tar.gz
```

**Comment by corbett5** [comment]
@TotoGaz you've put a lot of work into this, and I think it's certainly an improvement over our current situation. However if we are going to be using Spack for our TPL builds (say in the next four months), is it worth developers learning this new workflow / how to update the TPLs if we're just going to change to something completely different in the near future? Obviously it would have been good to talk about earlier and I'm not saying we shouldn't merge this but just thought I'd mention it.

**Comment by TotoGaz** [comment]
Hi @corbett5 

Regarding
```
[2020/10/13 00:28:32][   ERROR] module 'yaml' has no attribute 'FullLoader'
```
It's probably a version inconsistency, we can deal with it.

Then you have a lot of errors related to SSL unvalidated certificates.
I would bet that LLNL's proxy does some _man in the middle_ (or so) stuff. I've experience such things in my company.
One way would be to provide the actual certificate to the downloader, another would be to ignore those errors. 🤷‍♂️ 

Did you see the error multiple times or the script stops after the first (I would expect multiple times)?

Then, yes, the script does not stop at first error: it is supposed to "fail at end" so you can fix all the errors at once.
It's supposed to return a non-zero error code that must be checked; but it's true that we did not care too much.
If we had done so, it would have stopped.
On `travis-ci`, it's done by default (I think).

This is why you have 
```
[ 23%] Performing download step (verify and extract) for 'astyle'
CMake Error at astyle-stamp/verify-astyle.cmake:11 (message):
  File not found: /usr/WS2/corbett5/tpl-totogaz/tplMirror/astyle.tar.gz
```
The `astyle.tar.gz` has not been downloaded, but `cmake` still tries to build it.

As a conclusion, nothing we could not manage if we want to keep on going.

For the future `spack` direction, I do not care if we give up this work up.
Making this work is still some more work (+ future conflicts to deal with) and I would be glad avoiding it.
Up to you to decide.

**Comment by corbett5** [comment]
>
> Did you see the error multiple times or the script stops after the first (I would expect multiple times)?

Actually this was the only one.

@rrsettgast what do you think about this work in regards to Spack? If as Thomas says this will require more work it doesn't make sense to me to have him invest more time into it. Also as someone who will be working on the Spack build I'd like him to help me out haha.

**Comment by TotoGaz** [comment]
> > Did you see the error multiple times or the script stops after the first (I would expect multiple times)?
> 
> Actually this was the only one.

OK, then I do think it's because of `sourceforge`, they do not behave nicely... I do not understand what's going on though.
I can change and destination URL and use the backup instead.

**Comment by corbett5** [comment]
> 
> OK, then I do think it's because of `sourceforge`, they do not behave nicely... I do not understand what's going on though.
> I can change and destination URL and use the backup instead.

Cool, let me know when I should try it out again.

**Comment by TotoGaz** [comment]
> Cool, let me know when I should try it out again.

You can change the `astyle` url into `https://storage.googleapis.com/geosx-tpl-mirror/astyle.tar.gz/7712622f62661b1d8cb1062d7fedc390` (which is its backup location), and this should be OK.

**Comment by rrsettgast** [comment]
@corbett5 Yeah. Now that we are forced to used spack to enter the ElCap COE, this work will be replaced.

**Comment by corbett5** [comment]
When I tried the new link I got the same error, even when I tired a bogus link the same thing happened.

**Comment by TotoGaz** [comment]
> When I tried the new link I got the same error, even when I tired a bogus link the same thing happened.

This is weird... and did the other downloads go OK?

**Comment by corbett5** [comment]
They didn't download because they already existed. Would the url be cached anywhere? I didn't see any obvious byproducts.

**Comment by TotoGaz** [comment]
> They didn't download because they already existed. 

This is strange, the `tplMirror` is supposed to be quite empty... Maybe downloads from a first run?

> Would the url be cached anywhere? I didn't see any obvious byproducts.

Except those tarballs, there should be nothing changed 😢

**Comment by corbett5** [comment]
Yes they were downloaded from a previous run.

**Comment by TotoGaz** [comment]
> Yes they were downloaded from a previous run.

OK, I prefer this 😌 
Still don't understand why a download to google cloud platform would fail. Except a missing certificate, I do not get it.

Is
```bash
wget https://storage.googleapis.com/geosx-tpl-mirror/astyle.tar.gz/7712622f62661b1d8cb1062d7fedc390
```
working in a terminal?

**Comment by corbett5** [comment]
I added in a print statement when an exception occurs to print the name and url. With the google link I get
```
Error downloading tpl "astyle.tar.gz" from https://storage.googleapis.com/geosx-tpl-mirror/astyle.tar.gz/7712622f62661b1d8cb1062d7fedc390
[2020/10/13 17:58:00][   ERROR] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
Traceback (most recent call last):
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
```

Using ` https://storage.googleapis.com/geosx-tpl-mirror` I get the same error.
```Error downloading tpl "astyle.tar.gz" from https://storage.googleapis.com/geosx-tpl-mirror
[2020/10/13 18:01:36][   ERROR] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)
Traceback (most recent call last):
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/tce/packages/python/python-3.7.2/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

```

**Comment by corbett5** [comment]
> 
> 
> > Yes they were downloaded from a previous run.
> 
> OK, I prefer this 😌
> Still don't understand why a download to google cloud platform would fail. Except a missing certificate, I do not get it.
> 
> Is
> 
> ```shell
> wget https://storage.googleapis.com/geosx-tpl-mirror/astyle.tar.gz/7712622f62661b1d8cb1062d7fedc390
> ```
> 
> working in a terminal?

Yeah it produces a `7712622f62661b1d8cb1062d7fedc390` file, which I assume is the tarball by another name.

**Comment by TotoGaz** [comment]
OK, thanks for the investigation.

So I'm back to my first opinion. I think that LLNL's proxy is performing some man in the middle with self signed certificate deployed somewhere in the env.
Why only for this precise download? I don't know 🤷 
We could surely give this certificate to the script (see https://requests.readthedocs.io/en/master/user/advanced/#client-side-certificates).

However, it will take too much time.
If some day you can speak to some admin to know the truth 🕵️

**Pull request closed without merging**
